// SPDX-License-Identifier: MIT
// Copyright (c) 2025 Pablo Ulloa Santin

import { resolve } from "node:path";
import { fileURLToPath, URL } from "node:url";
import dts from "vite-plugin-dts";
import { defineConfig } from "vite-plus";

const rootDir = fileURLToPath(new URL(".", import.meta.url));
const toolIgnorePatterns = [
  "node_modules/**",
  "dist/**",
  "docs/**",
  "coverage/**",
  "stats/**",
  ".github/**",
  ".claude/**",
  ".codex/**",
  ".opencode/**",
  ".vite-hooks/**",
  "graphify-out/**",
  ".graphify_*",
  "**/*.md",
  "**/*.min.js",
  "**/*.min.css",
  "package-lock.json",
  "pnpm-lock.yaml",
];

export default defineConfig({
  staged: {
    "*": "vp check --fix",
  },
  lint: {
    ignorePatterns: toolIgnorePatterns,
    plugins: ["import", "typescript", "unicorn"],
    env: {
      browser: true,
      node: true,
    },
    options: {
      typeAware: true,
      typeCheck: true,
    },
    rules: {
      "constructor-super": "error",
      "for-direction": "error",
      "getter-return": "error",
      "import/no-commonjs": "error",
      "no-array-constructor": "error",
      "no-async-promise-executor": "error",
      "no-case-declarations": "error",
      "no-class-assign": "error",
      "no-compare-neg-zero": "error",
      "no-const-assign": "error",
      "no-constant-condition": "error",
      "no-control-regex": "error",
      "no-debugger": "error",
      "no-dupe-class-members": "error",
      "no-dupe-else-if": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty": "error",
      "no-empty-character-class": "error",
      "no-empty-pattern": "error",
      "no-ex-assign": "error",
      "no-extra-boolean-cast": "error",
      "no-fallthrough": "error",
      "no-func-assign": "error",
      "no-global-assign": "error",
      "no-import-assign": "error",
      "no-irregular-whitespace": "error",
      "no-loss-of-precision": "error",
      "no-misleading-character-class": "error",
      "no-new-native-nonconstructor": "error",
      "no-nonoctal-decimal-escape": "error",
      "no-obj-calls": "error",
      "no-prototype-builtins": "error",
      "no-redeclare": "error",
      "no-regex-spaces": "error",
      "no-self-assign": "error",
      "no-setter-return": "error",
      "no-shadow-restricted-names": "error",
      "no-sparse-arrays": "error",
      "no-this-before-super": "error",
      "no-undef": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-unsafe-optional-chaining": "error",
      "no-unused-labels": "error",
      "no-unused-private-class-members": "error",
      "no-unused-vars": "error",
      "no-useless-catch": "error",
      "no-useless-escape": "error",
      "no-var": "error",
      "no-with": "error",
      "prefer-const": "error",
      "prefer-rest-params": "error",
      "require-yield": "error",
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-extra-non-null-assertion": "error",
      "@typescript-eslint/no-misused-new": "error",
      "@typescript-eslint/no-namespace": "error",
      "@typescript-eslint/no-unnecessary-type-constraint": "error",
      "@typescript-eslint/no-unsafe-declaration-merging": "error",
      "@typescript-eslint/prefer-as-const": "error",
      "@typescript-eslint/prefer-namespace-keyword": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
    },
  },
  fmt: {
    ignorePatterns: toolIgnorePatterns,
    printWidth: 100,
    tabWidth: 2,
    useTabs: false,
    endOfLine: "lf",
    bracketSameLine: false,
    bracketSpacing: true,
    quoteProps: "as-needed",
    semi: true,
    singleQuote: false,
    jsxSingleQuote: false,
    trailingComma: "all",
    arrowParens: "always",
  },
  build: {
    lib: {
      entry: {
        "mlform/runtime": resolve(rootDir, "src/runtime/index.ts"),
        "mlform/schema": resolve(rootDir, "src/schema/index.ts"),
        "mlform/builtins": resolve(rootDir, "src/builtins/index.ts"),
        "mlform/primitives": resolve(rootDir, "src/primitives/index.ts"),
        "mlform/design": resolve(rootDir, "src/design/index.ts"),
        "mlform/kit": resolve(rootDir, "src/kit/index.ts"),
        "mlform/transport": resolve(rootDir, "src/transport/index.ts"),
      },
      name: "mlform",
      formats: ["es"],
      fileName: (_, mnt) => `${mnt}.mjs`,
    },
    outDir: "dist",
    emptyOutDir: true,
    minify: "oxc",
  },
  plugins: [
    dts({
      entryRoot: "src",
      include: ["src/**/*.ts"],
      outDirs: "dist/types",
      tsconfigPath: "./tsconfig.build.json",
    }),
  ],
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
      "mlform/runtime": resolve(rootDir, "src/runtime/index.ts"),
      "mlform/schema": resolve(rootDir, "src/schema/index.ts"),
      "mlform/builtins": resolve(rootDir, "src/builtins/index.ts"),
      "mlform/design": resolve(rootDir, "src/design/index.ts"),
      "mlform/kit": resolve(rootDir, "src/kit/index.ts"),
      "mlform/primitives": resolve(rootDir, "src/primitives/index.ts"),
      "mlform/transport": resolve(rootDir, "src/transport/index.ts"),
    },
  },
  define: {
    __DEV__: process.env.NODE_ENV !== "production",
  },
  test: {
    globals: true,
    environment: "jsdom",
    setupFiles: ["./test/setup.ts"],
    include: ["test/**/*.test.ts"],
    coverage: {
      reporter: ["html"],
      exclude: ["node_modules/", "test/", "dist/", "**/*.d.ts", "**/*.config.*", "**/coverage/**"],
      thresholds: {
        global: {
          branches: 80,
          functions: 80,
          lines: 80,
          statements: 80,
        },
      },
    },
    typecheck: {
      include: ["test/**/*.test.ts"],
    },
  },
});
