// SPDX-License-Identifier: MIT
// Copyright (c) 2025 Pablo Ulloa Santin

export { createSubmissionSnapshot, executeFormPipeline, executeReportFetches } from "./submission";
export { createMultiBackendSubmissionSnapshot, executeMultiBackendPipeline } from "./submission";
export type {
  CreateMultiBackendSubmissionSnapshotOptions,
  CreateSubmissionSnapshotOptions,
  ExecuteMultiBackendPipelineOptions,
  MultiBackendPipelineResult,
  MultiBackendRunResult,
  MultiBackendSubmit,
  SubmissionSnapshot,
} from "./submission";
export {
  EngineError,
  ReportPayloadError,
  RegistryError,
  SubmissionAbortedError,
  SubmitError,
  TransportError,
  transportErrorCodes,
  ValidationError,
} from "./errors";
export { createForm } from "./form";
export { shallowEquality } from "./equality";
export { removeFormSnapshot, restoreFormSnapshot, saveFormSnapshot } from "./snapshots";
export type {
  AllConditions,
  AfterSubmitContext,
  AfterValidateContext,
  AnyConditions,
  BaseFieldConfig,
  BaseReportConfig,
  BeforeSubmitContext,
  BeforeValidateContext,
  CreateFormConfig,
  DeclarativeFieldCondition,
  AfterReportFetchContext,
  FieldValidationFnContext,
  FieldValueAdapter,
  FieldConfig,
  FieldComparisonCondition,
  FieldCondition,
  FieldConditionContext,
  FieldController,
  FieldDefinition,
  FieldStateSnapshot,
  FieldStatus,
  FieldValueCondition,
  FieldValidationContext,
  FieldValidationResult,
  FormController,
  FormHooks,
  FormSchema,
  FormState,
  FormLifecycle,
  FormOperation,
  FormOperationCondition,
  FormPersistenceAdapter,
  FormSnapshot,
  FormSnapshotField,
  FormSnapshotSchemaEntry,
  FormSnapshotV1,
  FormSubmissionStatus,
  FormSubmissionStatusCondition,
  FormTransition,
  FormTransitionState,
  FormTransitionType,
  FormValidator,
  FormValidationContext,
  FormValidationIssue,
  FormValidationResult,
  InactiveFieldPolicy,
  JsonValue,
  MaybePromise,
  NormalizedFieldConfig,
  NormalizedReportConfig,
  Registry,
  ReportConfig,
  ReportController,
  ReportDefinition,
  ReportFetchContext,
  ReportFetchErrorContext,
  ReportFetchExecutionContext,
  ReportFetchExecutionResult,
  ReportFetchFactory,
  ReportFetchRequest,
  ReportFetchStatus,
  ReportFetchTransport,
  ReportContext,
  ReportResult,
  ReportResultContext,
  ReportResolveContext,
  ReportStateSnapshot,
  ReportStatus,
  PipelineArtifactAdapter,
  PipelineArtifactContext,
  PipelineResult,
  ExecuteFormPipelineOptions,
  SelectorSubscriptionOptions,
  SubmitCountCondition,
  SubmitErrorContext,
  SubmitOptions,
  SubmitRequest,
  SubmitResult,
  SubmissionInputRecord,
  Transport,
  TransportResponse,
  NotCondition,
  RuntimeBehavior,
  RuntimeBehaviorContext,
  RuntimeBehaviorSubmissionRecords,
  RuntimeBehaviorValueChangeEvent,
} from "./types";
