// SPDX-License-Identifier: MIT
// Copyright (c) 2025 Pablo Ulloa Santin

export {
  booleanFieldDefinition,
  categoryFieldDefinition,
  classifierReportDefinition,
  dateFieldDefinition,
  mappedCategoryFieldDefinition,
  longTextFieldDefinition,
  multiChoiceFieldDefinition,
  numberFieldDefinition,
  ratingFieldDefinition,
  regressorReportDefinition,
  seriesFieldDefinition,
  singleChoiceFieldDefinition,
  textFieldDefinition,
} from "./builtins";
export { createExplanationController } from "./explanations";
export { executeExplanations, executeFormPipeline } from "./submission";
export {
  EngineError,
  ReportPayloadError,
  RegistryError,
  SubmissionAbortedError,
  SubmitError,
  TransportError,
  transportErrorCodes,
  ValidationError,
} from "./errors";
export type { TransportErrorCode } from "./errors";
export { createForm, createForm as createFormRuntime } from "./form";
export {
  createRegistry,
  defineExplanationDefinition,
  defineFieldDefinition,
  defineReportDefinition,
} from "./registry";
export { defineExplanationKind, defineFieldKind, defineReportKind } from "@/presentation";
export {
  defaultEquality,
  shallowArrayEquality,
  shallowEquality,
  shallowObjectEquality,
} from "./equality";
export { identity, isPromiseLike } from "./utils";
export type {
  AfterExplanationContext,
  AllConditions,
  AfterSubmitContext,
  AfterValidateContext,
  AnyConditions,
  BaseExplanationConfig,
  BaseFieldConfig,
  BaseReportConfig,
  BeforeSubmitContext,
  BeforeValidateContext,
  ExplanationFetchContext,
  ExplanationFetchFactory,
  CreateFormConfig,
  DeclarativeFieldCondition,
  ExplanationConfig,
  ExplanationController,
  ExplanationDefinition,
  ExplanationErrorContext,
  ExplanationExecutionContext,
  ExplanationExecutionResult,
  ExplanationFetchRequest,
  ExplanationFetchTransport,
  ExplanationStateSnapshot,
  ExplanationStatus,
  FieldValidationFnContext,
  FieldValueAdapter,
  FieldConfig,
  FieldComparisonCondition,
  FieldCondition,
  FieldConditionContext,
  FieldController,
  FieldDefinition,
  FieldStateSnapshot,
  FieldStatus,
  FieldValueCondition,
  FieldValidationContext,
  FieldValidationResult,
  FormController,
  FormHooks,
  FormSchema,
  FormState,
  FormStatusCondition,
  FormStatus,
  FormValidator,
  FormValidationContext,
  FormValidationIssue,
  FormValidationResult,
  InactiveFieldPolicy,
  MaybePromise,
  NormalizedExplanationConfig,
  NormalizedFieldConfig,
  NormalizedReportConfig,
  Registry,
  ReportConfig,
  ReportController,
  ReportDefinition,
  ReportResolveContext,
  ReportStateSnapshot,
  ReportStatus,
  PipelineArtifactAdapter,
  PipelineArtifactContext,
  PipelineResult,
  ExecuteFormPipelineOptions,
  SelectorSubscriptionOptions,
  SubmitCountCondition,
  SubmitErrorContext,
  SubmitOptions,
  SubmitRequest,
  SubmitRequestTransportContext,
  SubmitResult,
  Transport,
  TransportAuthKind,
  TransportBackpressureMode,
  TransportCapabilities,
  TransportConsistency,
  TransportDeliveryMode,
  TransportPolicyContext,
  TransportSession,
  TransportSessionEvent,
  TransportSessionMessage,
  TransportStreamEvent,
  TransportResponse,
  NotCondition,
  RuntimeBehavior,
  RuntimeBehaviorContext,
  RuntimeBehaviorSubmissionRecords,
  RuntimeBehaviorValueChangeEvent,
} from "./types";
export type {
  DeclarativeExplanationKind,
  DeclarativeFieldKind,
  DeclarativeReportKind,
  ExplanationDescriptor,
  ExplanationDescriptorContext,
  ExplanationRenderSpec,
  ExplanationRenderSpecContext,
  FieldDescriptor,
  FieldRenderHints,
  FieldRenderSpec,
  FieldRenderSpecContext,
  FieldWidget,
  PresentationContent,
  PresentationNode,
  PresentationSummary,
  PresentationTone,
  ReportDescriptor,
  ReportRenderSpec,
  ReportRenderSpecContext,
} from "@/presentation";

export type FieldHandle = import("./types").FieldController;
export type ReportHandle = import("./types").ReportController;
export type ExplanationHandle = import("./types").ExplanationController;
export type FormRuntime = import("./types").FormController;
