// SPDX-License-Identifier: MIT
// Copyright (c) 2025 Pablo Ulloa Santin

export { executeFormPipeline, executeReportFetches } from "./submission";
export {
  EngineError,
  ReportPayloadError,
  RegistryError,
  SubmissionAbortedError,
  SubmitError,
  TransportError,
  transportErrorCodes,
  ValidationError,
} from "./errors";
export type { TransportErrorCode } from "./errors";
export { createForm, createForm as createFormRuntime } from "./form";
export {
  defaultEquality,
  shallowArrayEquality,
  shallowEquality,
  shallowObjectEquality,
} from "./equality";
export { identity, isPromiseLike } from "./utils";
export type {
  AllConditions,
  AfterSubmitContext,
  AfterValidateContext,
  AnyConditions,
  BaseFieldConfig,
  BaseReportConfig,
  BeforeSubmitContext,
  BeforeValidateContext,
  CreateFormConfig,
  DeclarativeFieldCondition,
  AfterReportFetchContext,
  FieldValidationFnContext,
  FieldValueAdapter,
  FieldConfig,
  FieldComparisonCondition,
  FieldCondition,
  FieldConditionContext,
  FieldController,
  FieldDefinition,
  FieldStateSnapshot,
  FieldStatus,
  FieldValueCondition,
  FieldValidationContext,
  FieldValidationResult,
  FormController,
  FormHooks,
  FormSchema,
  FormState,
  FormStatusCondition,
  FormStatus,
  FormValidator,
  FormValidationContext,
  FormValidationIssue,
  FormValidationResult,
  InactiveFieldPolicy,
  MaybePromise,
  NormalizedFieldConfig,
  NormalizedReportConfig,
  Registry,
  ReportConfig,
  ReportController,
  ReportDefinition,
  ReportFetchContext,
  ReportFetchErrorContext,
  ReportFetchExecutionContext,
  ReportFetchExecutionResult,
  ReportFetchFactory,
  ReportFetchRequest,
  ReportFetchStatus,
  ReportFetchTransport,
  ReportResolveContext,
  ReportStateSnapshot,
  ReportStatus,
  PipelineArtifactAdapter,
  PipelineArtifactContext,
  PipelineResult,
  ExecuteFormPipelineOptions,
  SelectorSubscriptionOptions,
  SubmitCountCondition,
  SubmitErrorContext,
  SubmitOptions,
  SubmitRequest,
  SubmitRequestTransportContext,
  SubmitResult,
  Transport,
  TransportAuthKind,
  TransportBackpressureMode,
  TransportCapabilities,
  TransportConsistency,
  TransportDeliveryMode,
  TransportPolicyContext,
  TransportSession,
  TransportSessionEvent,
  TransportSessionMessage,
  TransportStreamEvent,
  TransportResponse,
  NotCondition,
  RuntimeBehavior,
  RuntimeBehaviorContext,
  RuntimeBehaviorSubmissionRecords,
  RuntimeBehaviorValueChangeEvent,
} from "./types";

export type FieldHandle = import("./types").FieldController;
export type ReportHandle = import("./types").ReportController;
export type FormRuntime = import("./types").FormController;
