// SPDX-License-Identifier: MIT
// Copyright (c) 2025 Pablo Ulloa Santin

export { createBuiltinRegistry } from "./builtins";
export {
  booleanFieldDefinition,
  categoryFieldDefinition,
  classifierReportDefinition,
  dateFieldDefinition,
  numberFieldDefinition,
  regressorReportDefinition,
  textFieldDefinition,
  timeSeriesFieldDefinition,
} from "./builtins";
export { createExplanationController } from "./explanations";
export {
  EngineError,
  ReportPayloadError,
  RegistryError,
  SubmissionAbortedError,
  SubmitError,
  TransportError,
  transportErrorCodes,
  ValidationError,
} from "./errors";
export type { TransportErrorCode } from "./errors";
export { createForm } from "./form";
export {
  createRegistry,
  defineExplanationDefinition,
  defineFieldDefinition,
  defineReportDefinition,
  EngineRegistry,
} from "./registry";
export {
  defaultEquality,
  shallowArrayEquality,
  shallowEquality,
  shallowObjectEquality,
} from "./equality";
export { identity, isPromiseLike } from "./utils";
export type {
  AfterExplanationContext,
  AllConditions,
  AfterSubmitContext,
  AfterValidateContext,
  AnyConditions,
  BaseExplanationConfig,
  BaseFieldConfig,
  BaseReportConfig,
  BeforeSubmitContext,
  BeforeValidateContext,
  CreateFormConfig,
  DeclarativeFieldCondition,
  ExplanationConfig,
  ExplanationController,
  ExplanationDefinition,
  ExplanationDescriptor,
  ExplanationDescriptorContext,
  ExplanationErrorContext,
  ExplanationFetchRequest,
  ExplanationFetchTransport,
  ExplanationStateSnapshot,
  ExplanationStatus,
  FieldConfig,
  FieldComparisonCondition,
  FieldCondition,
  FieldConditionContext,
  FieldController,
  FieldDefinition,
  FieldDescriptor,
  FieldStateSnapshot,
  FieldStatus,
  FieldValueCondition,
  FieldValidationContext,
  FieldValidationResult,
  FormController,
  FormHooks,
  FormSchema,
  FormState,
  FormStatusCondition,
  FormStatus,
  FormValidator,
  FormValidationContext,
  FormValidationIssue,
  FormValidationResult,
  InactiveFieldPolicy,
  MaybePromise,
  NormalizedExplanationConfig,
  NormalizedFieldConfig,
  NormalizedReportConfig,
  Registry,
  ReportConfig,
  ReportController,
  ReportDefinition,
  ReportDescriptor,
  ReportStateSnapshot,
  ReportStatus,
  SelectorSubscriptionOptions,
  SubmitCountCondition,
  SubmitErrorContext,
  SubmitOptions,
  SubmitRequest,
  SubmitRequestTransportContext,
  SubmitResult,
  Transport,
  TransportAuthKind,
  TransportBackpressureMode,
  TransportCapabilities,
  TransportConsistency,
  TransportDeliveryMode,
  TransportPolicyContext,
  TransportSession,
  TransportSessionEvent,
  TransportSessionMessage,
  TransportStreamEvent,
  TransportResponse,
  NotCondition,
} from "./types";
