// SPDX-License-Identifier: MIT
// Copyright (c) 2025 Pablo Ulloa Santin

export {
  collectLayoutReferences,
  createFormView,
  defaultKitDesignSystem,
  defaultKitLabels,
  flattenLayoutNodes,
  mountForm,
  mountAccordionForm,
  mountTabsForm,
  mountWizardForm,
  unmountForm,
  walkLayoutNodes,
} from "@/kit";
export {
  assertPayloadWithinLimits,
  assertTransportCapabilities,
  cloneCapabilities,
  createFanoutTransport,
  createFallbackTransport,
  createGraphqlTransport,
  createGrpcSessionTransport,
  createGrpcStreamTransport,
  createGrpcTransport,
  createGrpcUnaryTransport,
  createHedgedTransport,
  createJsonTransport,
  createLoadBalancedTransport,
  createMemoryCircuitBreakerState,
  createMemorySharedRateLimiter,
  createMemoryTransportCacheStore,
  createMemoryTransportHealthState,
  createPipelineTransport,
  createQuorumFanoutTransport,
  createRacingTransport,
  createRoutingTransport,
  createSessionTransport,
  createSseTransport,
  createWebSocketSessionTransport,
  createWeightedRoutingTransport,
  inferTransportCapabilities,
  mergeTransportCapabilities,
  normalizeTransportCapabilities,
  pipe,
  transportDefaults,
  transportErrorMessages,
  transportErrorCodes,
  TransportError,
  withAuth,
  withCache,
  withCircuitBreaker,
  withDedup,
  withLogging,
  withMetrics,
  withRateLimit,
  withRequestTransform,
  withResponseTransform,
  withRetry,
  withTracing,
  withTimeout,
} from "@/transport";
export type {
  ApiKeyAuthOptions,
  AuthOptions,
  BearerAuthOptions,
  CacheOptions,
  CapabilityRequirement,
  CircuitBreakerOptions,
  CircuitBreakerSharedState,
  CircuitBreakerStateSnapshot,
  CustomAuthOptions,
  DedupOptions,
  FanoutTransportFailure,
  FanoutTransportOptions,
  FanoutTransportResult,
  FallbackTransportFailure,
  FallbackTransportOptions,
  GraphqlTransportOptions,
  GrpcSessionTransportOptions,
  GrpcStreamTransportOptions,
  GrpcTransportOptions,
  GrpcUnaryTransportOptions,
  HedgedTransportOptions,
  JsonTransportMethod,
  JsonTransportOptions,
  LoadBalancingTransportOptions,
  PipelineStage,
  PipelineTransportOptions,
  QuorumFanoutTransportOptions,
  RateLimitLeaseRequest,
  RateLimitOptions,
  RacingTransportOptions,
  RetryOptions,
  RoutingTransportOptions,
  SessionTransportOptions,
  SharedRateLimiter,
  SharedRateLimiterLease,
  SseTransportOptions,
  TransportBackpressureMode,
  TransportCacheEntry,
  TransportCacheStore,
  TransportCapabilities,
  TransportCollection,
  TransportConsistency,
  TransportContextAuthOptions,
  TransportDeliveryMode,
  TransportErrorCode,
  TransportHealthSnapshot,
  TransportHealthState,
  TransportLogOptions,
  TransportMetricsOptions,
  TransportMiddleware,
  TransportTelemetryEvent,
  TransportTraceOptions,
  WebSocketSessionTransportOptions,
  WeightedRoutingTransportOptions,
} from "@/transport";
export type {
  AccordionLayoutConfig,
  AccordionMountUiOptions,
  AccordionSectionConfig,
  AccordionState,
  CreateFormViewOptions,
  FormLayoutConfig,
  FormLayoutExplanationNode,
  FormLayoutFieldNode,
  FormLayoutGroupNode,
  FormLayoutNode,
  FormLayoutReportNode,
  FormLayoutSectionNode,
  FormViewController,
  FormViewExplanationItem,
  FormViewFieldItem,
  FormViewReportItem,
  FormViewSnapshot,
  FormViewState,
  KitDesignSystemSnapshot,
  KitLabels,
  MountedAccordionForm,
  MountFormOptions,
  MountedForm,
  MountedTabsForm,
  MountedWizardForm,
  MountAccordionFormOptions,
  MountTabsFormOptions,
  MountWizardFormOptions,
  PanelState,
  ResolvedAccordionLayout,
  ResolvedAccordionSection,
  ResolvedFormLayout,
  ResolvedFormLayoutExplanationNode,
  ResolvedFormLayoutFieldNode,
  ResolvedFormLayoutGroupNode,
  ResolvedFormLayoutNode,
  ResolvedFormLayoutReportNode,
  ResolvedFormLayoutSectionNode,
  ResolvedTabLayout,
  ResolvedTabsLayout,
  TabLayoutConfig,
  TabsLayoutConfig,
  TabsState,
  WizardLayoutConfig,
  WizardState,
  WizardStepConfig,
} from "@/kit";
export type {
  ExplanationRequest,
  ExplanationTransport,
  PrimitiveFieldRenderContext,
  PrimitiveExplanationRenderContext,
  PrimitiveExplanationRendererElement,
  PrimitiveFieldRendererElement,
  PrimitiveReportRenderContext,
  PrimitiveReportRendererElement,
} from "@/primitives";
export { createExplanationController, executeExplanations, executeFormPipeline } from "@/runtime";
export {
  createRegistry,
  defineExplanationDefinition,
  defineFieldDefinition,
  defineReportDefinition,
} from "@/schema";
export {
  defineExplanationKind,
  defineFieldKind,
  defineReportKind,
  toPresentationNodes,
} from "@/presentation";
export { createBuiltinMlRegistry, createMlRegistryPack } from "@/builtins-ml";
export { createMappedCategoryBehavior } from "@/behaviors";
export { createDefaultRegistryPack } from "@/packs";
export type {
  AfterExplanationContext,
  ExplanationConfig,
  ExplanationController,
  ExplanationDefinition,
  ExplanationErrorContext,
  ExplanationExecutionContext,
  ExplanationExecutionResult,
  ExplanationFetchContext,
  ExplanationFetchFactory,
  ExplanationFetchRequest,
  ExplanationFetchTransport,
  ExplanationStateSnapshot,
  ExplanationStatus,
  FieldValidationFnContext,
  FieldValueAdapter,
  NormalizedExplanationConfig,
  PipelineArtifactAdapter,
  PipelineArtifactContext,
  PipelineResult,
  ExecuteFormPipelineOptions,
  ReportResolveContext,
} from "@/runtime";
export type {
  DeclarativeExplanationKind,
  DeclarativeFieldKind,
  DeclarativeReportKind,
  ExplanationDescriptor,
  ExplanationDescriptorContext,
  ExplanationRenderSpec,
  ExplanationRenderSpecContext,
  FieldDescriptor,
  FieldRenderHints,
  FieldRenderSpec,
  FieldRenderSpecContext,
  FieldWidget,
  PresentationContent,
  PresentationNode,
  PresentationSummary,
  PresentationTone,
  ReportDescriptor,
  ReportRenderSpec,
  ReportRenderSpecContext,
} from "@/presentation";
